Ais\UserBundle\Entity\AccessToken:
 type: entity
 table: access_token
 id:
  id:
   type: integer
   generator: { strategy: AUTO }

 manyToOne:
  client:
   targetEntity: Client
   inversedBy: accessToken
   joinColumn:
    name: client
    referencedColumnName: id
  user:
   targetEntity: User
   inversedBy: accessToken
   joinColumn:
    name: user
    referencedColumnName: id
