Ais\UserBundle\Entity\Client:
 type: entity
 table: client
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 oneToMany:
  accessToken:
   targetEntity: AccessToken
   mappedBy: client
  refreshToken:
   targetEntity: RefreshToken
   mappedBy: client
  authCode:
   targetEntity: AuthCode
   mappedBy: client
